### ISSUE TITLE
URL Request doesn't seem to support accented characters

### ISSUE THREAD

**Issue by gs-101** [karthink/gptel-quick#2]
The request seems to break when using fragments with accented characters as an argument. Take the phrase "movimento harmônico simples" (simple harmonic motion), the request outputs the following text to the *messages* buffer as an error:

<details>

  ```
url-http-create-request: Multibyte text in HTTP request: POST /chat/completions HTTP/1.1^M
  MIME-Version: 1.0^M
  Connection: keep-alive^M
  Hosts: models.inference.ai.azure.com^M
  Accept-encoding: gzip^M
  Accept: */*^M
  User-Agent: URL/Emacs Emacs/31.0.50 (PureGTK, x86_64-pc-linux-gnu)^M
  Content-Type: application/json^M
  Authorization: Bearer $GITHUB_TOKEN^M
  Content-length: 197^M
  ^M
  {"model":"gpt-4o","messages":[{"role":"system","content":"Explain in 12 words or fewer."},{"role":"user","content":"Movimento Harm\303\264nico Simples"}],"stream":false,"temperature":1.0,"max_tokens":35}
  ```

</details>

This doesn't happen with sentences without accented characters, and as you can see the "ô" is replaced with "\303\264" in the request. The gptel buffer also has no problems with accented characters.

**Comment by karthink** [comment]
I remember fixing this in gptel, hmm.  Can you try with Curl? `(setq gptel-use-curl t)`

**Comment by karthink** [comment]
I couldn't reproduce the error, by the way.

**Comment by gs-101** [comment]
> EDIT:Are you on the latest commit of `gptel`?

`gptel` is version `20240917.2304` from MELPA, commit `8788060` (the latest commit). But I could try reinstalling it.

> I couldn't reproduce the error, by the way.

Test before reinstalling: same issue with a phrase with acute (´) accentuation ("meios translúcidos", translucent spaces), no issue with non-accented phrases/words. Message output is written as "meios transl\303\272cidos".

Test after reinstalling: same issue, `gptel-quick` is also in the latest commit, `54f1c65`

I tried sending a message with `M-: (message "Movimento Harmônico Simples")` and it displays the accents just fine in the message buffer, no issues.

I think the main issue lies on how the characters are being converted:
![image](https://github.com/user-attachments/assets/2d895e55-888f-4b6d-bf78-2edd1633d731)
But you can discard this option if I'm incorrect.

Additional things that could be of note:

- I'm using the brazilian portuguese keyboard layout.
- I tried sending a curl request on the terminal with the phrase initially mentioned on the issue and had success.

**Comment by gs-101** [comment]
Not sure how it happened, but it's working correctly. Maybe it was an issue with my configuration.
Closing this issue for now.
